name: ItemTransfer
version: '${minecraft.plugin.version}'
main: de.minebench.itemtransfer.ItemTransfer
api-version: 1.19
softdepend: [OpenInv]
authors: [ Phoenix616 ]
description: '${project.description}'
source: "${project.scm.url}"
inform-user: true
license: '${minecraft.plugin.license}'
license-terms: |-
  ${minecraft.plugin.license-terms}
commands:
  itemtransfer:
    usage: /<command> info|reload
    description: Main plugin command
    permission: itemtransfer.command
  storeitems:
    usage: /<command> [<player>]
    description: Store items
    permission: itemtransfer.command.storeitems
    aliases: [transferitems,senditems,storeitem,transferitem,senditem]
  getitems:
    usage: /<command> [<player>]
    description: Get stored items
    permission: itemtransfer.command.getitems
    aliases: [getitem]
  storeallplayers:
    usage: /<command>
    description: Store items for all players
    permission: itemtransfer.command.storeallplayers
    aliases: [storeplayers]
permissions:
  itemtransfer.command:
    default: true
    description: Plugin command permission
  itemtransfer.command.info:
    default: true
    description: Permission to view plugin information
  itemtransfer.command.reload:
    default: op
    description: Permission to the reload command
  itemtransfer.command.storeitems:
    default: op
    description: Permission to store items
  itemtransfer.command.storeitems.others:
    default: op
    description: Permission to store items for others
  itemtransfer.command.getitems:
    default: op
    description: Permission to get items
  itemtransfer.command.getitems.others:
    default: op
    description: Permission to get items for others
  itemtransfer.click.storeitems:
    default: op
    description: Permission to click a block to open a gui to store items
  itemtransfer.click.getitems:
    default: op
    description: Permission to click a block to open a gui to get the items
  itemtransfer.click.storeallplayers:
    default: op
    description: Permission to store items for all players